version: "3.8"

services:

  watchtower:
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment:
      - WATCHTOWER_LABEL_ENABLE=true

  # Enabling watchtower for our own images
  crowsnest-frontend:
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
